print('_'*27)
print('='*4,'ALUGUEL DE CARROS','='*4)
print('_'*27)
km=float(input('por quantos dias usou o carro?'))
d=float(input('quantos km foram rodados'))
print(f'O total a pagar é de R${km * 60 + d * 0.15:.2f}')
